
server:
  port: 8090
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 620302

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wms.entity
  global-config:
    db-config:
      id-type: auto

Logging:
  level:
    com.wms: debug